export const FETCH_BOOKS_REQUEST = "FETCH_BOOKS_REQUEST";
export const FETCH_BOOKS_SUCCESS = "FETCH_BOOKS_SUCCESS";
export const FETCH_BOOKS_ERROR = "FETCH_BOOKS_ERROR";

export const ADD_BOOK_CART = "ADD_BOOK_CART";
export const REMOVE_BOOK_CART = "REMOVE_BOOK_CART";
export const SET_BOOK_CART = "SET_BOOK_CART";

export const INIT_BOOKS_STATE = "INIT_PRODUCTS_STATE";
